name: Deploy Django Project

on:
  push:
    branches:
      - main  # Выполнять при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout репозитория
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Установить SSH-ключ для доступа к серверу
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Добавьте SSH-ключ в Secrets репозитория

    # 3. Выполнить команды на удалённом сервере
    - name: Deploy on Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@185.22.67.9 << 'EOF'
          # Перейти в директорию проекта
          cd /var/www/workflow

          # 1. Обновить код из репозитория
          git pull origin main

          # 2. Активировать виртуальное окружение
          source venv/bin/activate

          # 3. Установить зависимости
          pip install -r requirements.txt

          # 4. Применить миграции базы данных
          python manage.py migrate

          # 5. Собрать статические файлы
          python manage.py collectstatic --noinput

          # 6. Перезапустить Gunicorn
          sudo systemctl restart myproject

          # 7. Перезагрузить Nginx (если нужно)
          sudo systemctl reload nginx
        EOF